services:
  multi-slm:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: multi-slm-kyle
    shm_size: 16g
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OLLAMA_FLASH_ATTENTION=1
    volumes:
      - .:/app
    ports:
      - "8501:8501"
      - "8000:8000"
      - "8889:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ['0', '1', '2', '3'] # 或者 ['all'] 以使用全部 GPU
    command: >
      jupyter lab
        --ip=0.0.0.0
        --port=8888
        --no-browser
        --allow-root
        --ServerApp.token=''
        --ServerApp.password=''
# docker exec -it minions_container bash
